import React, { useState, useEffect } from 'react'
import { getBrowse } from '../utils/api'
import Head from 'next/head'
import Link from "next/link"
import styled from '@emotion/styled'

import MovieList from '../components/MovieList'
import { Pagination, useMediaQuery } from '@mui/material'
import Navbar from '../components/Navbar'
import Footer from '../components/Footer'

const Section = styled.section`
    height: 100%;
`;

const Main = styled.main`
    padding-left: 16px;
    padding-right: 16px;
    padding-top: 75px;
    @media (min-width: 768px) {
        padding-top: 85px;
    }
    @media (min-width: 1280px) {
        max-width: 1060px;
        margin: 0 auto;
    }
`;

const WrapperPagination = styled.div`
	text-align: center;
	margin: 0 auto;
	display: block;
	margin-bottom: 50px;
	margin-top: 20px;
`;

const CustomPagination = styled(Pagination)`
	margin: 0 auto;
	display: inline-flex;
`;

export default function Home() {

	const isMobile = useMediaQuery('(max-width:425px)')

	const [movies, setMovies] = useState([])
	const [favourite, setFavourites] = useState([])
    const [loading, setLoading] = useState(true)
    const [error, setError] = useState(false)
	const [totalMovies, setTotalMovies] = useState()
	const [page, setPage] = useState(1)

	const handleChangePage = (event, value) => {
		setPage(value);
	}

	useEffect(() => {
		getBrowse('dune', page)
			.then(res => {
				setLoading(true);
				setMovies(res.data.Search)
				setTotalMovies(Math.ceil(res.data.totalResults/10))
				setLoading(false);
				setError(false);
			})
			.catch(err => {
				console.log(err)
				setError(true);
			});
		window.scrollTo(0, 0);
	}, [page]);
	
	if (error || !movies) {
		return (
			<div >
				<span>Error, please go to <b><Link href="/">homepage</Link></b></span>
			</div>
		);
	}

  	return (
		<>
			<Head>
				<title>Next Movie</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Navbar />

			<Section>	
				<Main>
					<h2>
						Browse thousands of movies
						through OMDB API.
					</h2>

					{loading ? (
						<span>Loading ...</span>
					) : (
						<React.Fragment>
							<MovieList movies={movies} />

							<WrapperPagination>
								<CustomPagination
									count={totalMovies}
									size={isMobile ? "small" : "large"}
									page={page}
									variant="outlined"
									shape="rounded"
									onChange={handleChangePage}
								/>
							</WrapperPagination>
						</React.Fragment>
					)}
					
				</Main>

				<Footer />
			</Section>

			
		
		</>
  	)
}